In [1]:
# Numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
np.__version__

In [10]:
np.random.randint(1,5,3)

array([2, 3, 1])

In [12]:
np.random.rand(3)

array([0.8560639 , 0.28337633, 0.97127406])

In [13]:
np.random.rand(5,2,3)

array([[[7.45711332e-01, 9.83689039e-01, 7.49485861e-01],
        [4.89484335e-01, 7.33053387e-01, 2.20702844e-02]],

       [[6.38079004e-01, 2.86975872e-01, 1.74163583e-01],
        [4.22937455e-01, 1.61543589e-01, 4.45874294e-01]],

       [[9.31172359e-01, 9.15116528e-01, 1.01845027e-01],
        [1.37970347e-01, 5.72698484e-01, 1.62060309e-01]],

       [[1.20705613e-01, 9.52867822e-01, 3.40052385e-01],
        [3.54319968e-01, 2.72817351e-04, 3.46465788e-01]],

       [[6.93356252e-01, 1.53817644e-01, 4.76501134e-01],
        [8.16125870e-01, 2.94909681e-01, 5.70199792e-01]]])

In [14]:
np.random.randint(5,2,3)

ValueError: low >= high

In [15]:
np.random.rand(-5,2,3)

ValueError: negative dimensions are not allowed

In [16]:
np.random.randint(-5,2,3)

array([-2, -3, -3])

In [17]:
np.random.randint(10,40,(10,10))

array([[27, 32, 33, 18, 37, 38, 16, 27, 37, 31],
       [27, 18, 25, 10, 31, 29, 12, 24, 22, 15],
       [37, 34, 16, 26, 27, 12, 35, 16, 16, 18],
       [11, 35, 13, 33, 24, 37, 37, 24, 31, 13],
       [13, 24, 39, 22, 13, 13, 27, 17, 26, 30],
       [13, 16, 12, 29, 17, 19, 21, 39, 16, 37],
       [14, 11, 38, 16, 25, 34, 32, 20, 32, 25],
       [18, 28, 17, 17, 13, 19, 23, 12, 19, 23],
       [16, 26, 26, 20, 23, 13, 12, 18, 20, 32],
       [31, 26, 35, 35, 24, 21, 14, 21, 37, 24]])

In [20]:
ri = np.random.randint(10,40,(10,10))
len(ri)

10

In [26]:
ri = np.random.randint(10,40,(3,5))
len(ri)

3

In [27]:
ri.shape

(3, 5)

In [23]:
id(ri)

1726755043824

In [25]:

#Slicing in numpy

In [28]:
ri[1]

array([37, 24, 23, 28, 14])

In [29]:
ri[0:3]

array([[18, 23, 10, 34, 36],
       [37, 24, 23, 28, 14],
       [35, 20, 25, 26, 25]])

In [30]:
ri

array([[18, 23, 10, 34, 36],
       [37, 24, 23, 28, 14],
       [35, 20, 25, 26, 25]])

In [31]:
ri_1 = np.random.randint(10,40,(10,10))

In [32]:
ri_1

array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [34]:
ri_1.shape


(10, 10)

In [35]:
print(ri_1)

[[11 16 27 15 39 25 24 15 12 14]
 [26 21 13 32 13 17 10 19 24 33]
 [26 34 15 25 35 27 11 27 20 34]
 [10 22 22 33 36 10 39 16 28 24]
 [15 32 26 24 13 30 16 16 28 37]
 [19 23 18 35 28 19 29 18 28 37]
 [10 17 13 23 20 30 10 15 20 38]
 [15 19 35 16 38 23 13 21 30 37]
 [10 36 18 25 13 31 20 13 27 22]
 [22 32 16 37 16 17 12 29 24 21]]


In [36]:
ri_1[:]


array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [37]:
ri_1[3:8]

array([[10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37]])

In [38]:
ri_1[3,8]

28

In [39]:
ri_1[3:8:-1]

array([], shape=(0, 10), dtype=int32)

In [41]:
ri_1[-5]

array([19, 23, 18, 35, 28, 19, 29, 18, 28, 37])

In [42]:
ri_1[-5,-3]

18

In [44]:
print(ri_1)
ri_1[::3]

[[11 16 27 15 39 25 24 15 12 14]
 [26 21 13 32 13 17 10 19 24 33]
 [26 34 15 25 35 27 11 27 20 34]
 [10 22 22 33 36 10 39 16 28 24]
 [15 32 26 24 13 30 16 16 28 37]
 [19 23 18 35 28 19 29 18 28 37]
 [10 17 13 23 20 30 10 15 20 38]
 [15 19 35 16 38 23 13 21 30 37]
 [10 36 18 25 13 31 20 13 27 22]
 [22 32 16 37 16 17 12 29 24 21]]


array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [45]:
print(ri_1[::-1])

[[22 32 16 37 16 17 12 29 24 21]
 [10 36 18 25 13 31 20 13 27 22]
 [15 19 35 16 38 23 13 21 30 37]
 [10 17 13 23 20 30 10 15 20 38]
 [19 23 18 35 28 19 29 18 28 37]
 [15 32 26 24 13 30 16 16 28 37]
 [10 22 22 33 36 10 39 16 28 24]
 [26 34 15 25 35 27 11 27 20 34]
 [26 21 13 32 13 17 10 19 24 33]
 [11 16 27 15 39 25 24 15 12 14]]


In [46]:
ri_1[::-1]

array([[22, 32, 16, 37, 16, 17, 12, 29, 24, 21],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [11, 16, 27, 15, 39, 25, 24, 15, 12, 14]])

In [47]:

ri_1[::-5]

array([[22, 32, 16, 37, 16, 17, 12, 29, 24, 21],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37]])

In [48]:
ri_1

array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [49]:
ri_1[::-5]

array([[22, 32, 16, 37, 16, 17, 12, 29, 24, 21],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37]])

In [50]:
ri_1[::2]

array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22]])

In [51]:
ri_1[::-2]

array([[22, 32, 16, 37, 16, 17, 12, 29, 24, 21],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33]])

In [52]:
ri_1[2]

array([26, 34, 15, 25, 35, 27, 11, 27, 20, 34])

In [54]:
ri_1

array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [55]:
ri_1[:,2]# It will print the column

array([27, 13, 15, 22, 26, 18, 13, 35, 18, 16])

In [56]:
ri_1[2] # print the specific columns

array([26, 34, 15, 25, 35, 27, 11, 27, 20, 34])

In [57]:
ri_1[:,8]

array([12, 24, 20, 28, 28, 28, 20, 30, 27, 24])

In [58]:
ri_1[:,-8] # in , it will retrive the exact column in case of : it give n-1 column

array([27, 13, 15, 22, 26, 18, 13, 35, 18, 16])

In [62]:
ri_1

array([[11, 16, 27, 15, 39, 25, 24, 15, 12, 14],
       [26, 21, 13, 32, 13, 17, 10, 19, 24, 33],
       [26, 34, 15, 25, 35, 27, 11, 27, 20, 34],
       [10, 22, 22, 33, 36, 10, 39, 16, 28, 24],
       [15, 32, 26, 24, 13, 30, 16, 16, 28, 37],
       [19, 23, 18, 35, 28, 19, 29, 18, 28, 37],
       [10, 17, 13, 23, 20, 30, 10, 15, 20, 38],
       [15, 19, 35, 16, 38, 23, 13, 21, 30, 37],
       [10, 36, 18, 25, 13, 31, 20, 13, 27, 22],
       [22, 32, 16, 37, 16, 17, 12, 29, 24, 21]])

In [63]:
ri_1[2:6,5:8]

array([[27, 11, 27],
       [10, 39, 16],
       [30, 16, 16],
       [19, 29, 18]])

In [64]:
ri_1[0:3,0:3]

array([[11, 16, 27],
       [26, 21, 13],
       [26, 34, 15]])

In [65]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [68]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [71]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [73]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [75]:
mat =np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mat =np.arange(0,100).reshape(10,10)
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
id(mat)

1726754539536

In [79]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [80]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [82]:
mat[mat==50]

array([50])

In [83]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])