In [1]:
#Numpy Crash course

In [2]:
print("Numpy Crash course")

Numpy Crash course


In [4]:
import numpy as np


In [6]:
np.__version__

'1.26.4'

In [7]:
install numpy

SyntaxError: invalid syntax (353274537.py, line 1)

In [8]:
 pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [9]:
np.amin

<function amin at 0x00000259413B8E30>

In [11]:
from numpy import * # we are calling all 256 functions togehter at once

In [12]:
my_list =[0,1,2,3,4,5]


[0, 1, 2, 3, 4, 5]

In [13]:
type(my_list)

list

In [14]:
arr =np.array(my_list)

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
type(arr)

numpy.ndarray

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros(5,dtype=int) # 1D Arrays

array([0, 0, 0, 0, 0])

In [31]:
np.zeros((2,2))  # 2D Arrays

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros((2,2), dtype=int)  # 2D Arrays 2x2 -Matrix

array([[0, 0],
       [0, 0]])

In [33]:
np.zeros((5,10), dtype=int)  # 2D Arrays 5x10 -Matrix -ND - Array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
np.twos((3,3), dtype=int)

AttributeError: module 'numpy' has no attribute 'twos'

In [42]:
np.random.rand(4) #Number suffel on each time we execute

array([0.47175612, 0.36359559, 0.58286456, 0.96163164])

In [43]:
np.random.rand(4,4)

array([[0.85935364, 0.69864086, 0.54488157, 0.89383591],
       [0.23566029, 0.22094975, 0.75588557, 0.92956284],
       [0.07856675, 0.95875494, 0.92815902, 0.14554394],
       [0.88856586, 0.85144448, 0.94181649, 0.97086654]])

In [46]:
np.random.randint(3) # it will print values from 0 to 3-1 that is between 0-2

0

In [51]:
np.random.randint(1,32)  # it will print values between 0- 31

6